package com.myteam.rulesbase;

import com.myteam.rulesbase.dedupCases;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class dedupCaseList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("case1")
	private com.myteam.rulesbase.dedupCases case1;

	@org.kie.api.definition.type.Label("case2")
	private com.myteam.rulesbase.dedupCases case2;

	@org.kie.api.definition.type.Label("dupMeta")
	private java.lang.Boolean dupMeta;

	@org.kie.api.definition.type.Label("dupIncType")
	private java.lang.Boolean dupIncType;

	@org.kie.api.definition.type.Label("dupVehReg")
	private java.lang.Boolean dupVehReg;

	@org.kie.api.definition.type.Label("dupDOB")
	private java.lang.Boolean dupDOB;

	@org.kie.api.definition.type.Label("dupCaseStatus")
	private java.lang.String dupCaseStatus;

	@org.kie.api.definition.type.Label("dupCaseOwner")
	private java.lang.String dupCaseOwner;

	@org.kie.api.definition.type.Label("isDuplicate")
	private java.lang.Boolean isDuplicate;

	@org.kie.api.definition.type.Label(value = "dupSaId")
	private java.lang.Boolean dupSaId;

	public dedupCaseList() {
	}

	public com.myteam.rulesbase.dedupCases getCase1() {
		return this.case1;
	}

	public void setCase1(com.myteam.rulesbase.dedupCases case1) {
		this.case1 = case1;
	}

	public com.myteam.rulesbase.dedupCases getCase2() {
		return this.case2;
	}

	public void setCase2(com.myteam.rulesbase.dedupCases case2) {
		this.case2 = case2;
	}

	public java.lang.Boolean getDupMeta() {
		return this.dupMeta;
	}

	public void setDupMeta(java.lang.Boolean dupMeta) {
		this.dupMeta = dupMeta;
	}

	public java.lang.Boolean getDupIncType() {
		return this.dupIncType;
	}

	public void setDupIncType(java.lang.Boolean dupIncType) {
		this.dupIncType = dupIncType;
	}

	public java.lang.Boolean getDupVehReg() {
		return this.dupVehReg;
	}

	public void setDupVehReg(java.lang.Boolean dupVehReg) {
		this.dupVehReg = dupVehReg;
	}

	public java.lang.Boolean getDupDOB() {
		return this.dupDOB;
	}

	public void setDupDOB(java.lang.Boolean dupDOB) {
		this.dupDOB = dupDOB;
	}

	public java.lang.String getDupCaseStatus() {
		return this.dupCaseStatus;
	}

	public void setDupCaseStatus(java.lang.String dupCaseStatus) {
		this.dupCaseStatus = dupCaseStatus;
	}

	public java.lang.String getDupCaseOwner() {
		return this.dupCaseOwner;
	}

	public void setDupCaseOwner(java.lang.String dupCaseOwner) {
		this.dupCaseOwner = dupCaseOwner;
	}

	public java.lang.Boolean getIsDuplicate() {
		return this.isDuplicate;
	}

	public void setIsDuplicate(java.lang.Boolean isDuplicate) {
		this.isDuplicate = isDuplicate;
	}

	public java.lang.Boolean getDupSaId() {
		return this.dupSaId;
	}

	public void setDupSaId(java.lang.Boolean dupSaId) {
		this.dupSaId = dupSaId;
	}

	public dedupCaseList(com.myteam.rulesbase.dedupCases case1,
			com.myteam.rulesbase.dedupCases case2, java.lang.Boolean dupMeta,
			java.lang.Boolean dupIncType, java.lang.Boolean dupVehReg,
			java.lang.Boolean dupDOB, java.lang.String dupCaseStatus,
			java.lang.String dupCaseOwner, java.lang.Boolean isDuplicate,
			java.lang.Boolean dupSaId) {
		this.case1 = case1;
		this.case2 = case2;
		this.dupMeta = dupMeta;
		this.dupIncType = dupIncType;
		this.dupVehReg = dupVehReg;
		this.dupDOB = dupDOB;
		this.dupCaseStatus = dupCaseStatus;
		this.dupCaseOwner = dupCaseOwner;
		this.isDuplicate = isDuplicate;
		this.dupSaId = dupSaId;
	}

}