package com.myteam.rulesbase;

import java.time.OffsetDateTime;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class dateCollection implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("dateStart")
	private OffsetDateTime dateStart;
	@org.kie.api.definition.type.Label("dateEnd")
	private OffsetDateTime dateEnd;
	@org.kie.api.definition.type.Label("dateDifference")
	private OffsetDateTime dateDifference;

	public dateCollection() {
	}

	public java.time.OffsetDateTime getDateStart() {
		return this.dateStart;
	}

	public void setDateStart(java.time.OffsetDateTime dateStart) {
		this.dateStart = dateStart;
	}

	public java.time.OffsetDateTime getDateEnd() {
		return this.dateEnd;
	}

	public void setDateEnd(java.time.OffsetDateTime dateEnd) {
		this.dateEnd = dateEnd;
	}

	public java.time.OffsetDateTime getDateDifference() {
		return this.dateDifference;
	}

	public void setDateDifference(java.time.OffsetDateTime dateDifference) {
		this.dateDifference = dateDifference;
	}

	public dateCollection(java.time.OffsetDateTime dateStart,
			java.time.OffsetDateTime dateEnd,
			java.time.OffsetDateTime dateDifference) {
		this.dateStart = dateStart;
		this.dateEnd = dateEnd;
		this.dateDifference = dateDifference;
	}

}