package com.myteam.rulesbase;

import java.time.OffsetDateTime;
import java.time.LocalDateTime;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class dedupCases implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("policyNo")
	private java.lang.String policyNo;
	@org.kie.api.definition.type.Label("incidentTime")
	private LocalDateTime incidentTime;
	@org.kie.api.definition.type.Label("location")
	private java.lang.String location;
	@org.kie.api.definition.type.Label("vehicleRegNo")
	private java.lang.String vehicleRegNo;
	@org.kie.api.definition.type.Label("saId")
	private java.lang.String saId;
	@org.kie.api.definition.type.Label("customerInitials")
	private java.lang.String customerInitials;
	@org.kie.api.definition.type.Label("customerSurname")
	private java.lang.String customerSurname;
	@org.kie.api.definition.type.Label("dateOfBirth")
	private java.lang.String dateOfBirth;
	@org.kie.api.definition.type.Label("vehicleIncidentType")
	private java.lang.String vehicleIncidentType;
	@org.kie.api.definition.type.Label("vehicleIncidentSubtype")
	private java.lang.String vehicleIncidentSubtype;

	@org.kie.api.definition.type.Label("policyHolderId")
	private java.lang.String policyHolderId;

	@org.kie.api.definition.type.Label("caseStatus")
	private java.lang.String caseStatus;

	public dedupCases() {
	}

	public java.lang.String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(java.lang.String policyNo) {
		this.policyNo = policyNo;
	}

	public java.lang.String getLocation() {
		return this.location;
	}

	public void setLocation(java.lang.String location) {
		this.location = location;
	}

	public java.lang.String getVehicleRegNo() {
		return this.vehicleRegNo;
	}

	public void setVehicleRegNo(java.lang.String vehicleRegNo) {
		this.vehicleRegNo = vehicleRegNo;
	}

	public java.lang.String getSaId() {
		return this.saId;
	}

	public void setSaId(java.lang.String saId) {
		this.saId = saId;
	}

	public java.lang.String getCustomerInitials() {
		return this.customerInitials;
	}

	public void setCustomerInitials(java.lang.String customerInitials) {
		this.customerInitials = customerInitials;
	}

	public java.lang.String getCustomerSurname() {
		return this.customerSurname;
	}

	public void setCustomerSurname(java.lang.String customerSurname) {
		this.customerSurname = customerSurname;
	}

	public java.lang.String getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(java.lang.String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public java.lang.String getVehicleIncidentType() {
		return this.vehicleIncidentType;
	}

	public void setVehicleIncidentType(java.lang.String vehicleIncidentType) {
		this.vehicleIncidentType = vehicleIncidentType;
	}

	public java.lang.String getVehicleIncidentSubtype() {
		return this.vehicleIncidentSubtype;
	}

	public void setVehicleIncidentSubtype(
			java.lang.String vehicleIncidentSubtype) {
		this.vehicleIncidentSubtype = vehicleIncidentSubtype;
	}

	public java.lang.String getPolicyHolderId() {
		return this.policyHolderId;
	}

	public void setPolicyHolderId(java.lang.String policyHolderId) {
		this.policyHolderId = policyHolderId;
	}

	public java.lang.String getCaseStatus() {
		return this.caseStatus;
	}

	public void setCaseStatus(java.lang.String caseStatus) {
		this.caseStatus = caseStatus;
	}

	public java.time.LocalDateTime getIncidentTime() {
		return this.incidentTime;
	}

	public void setIncidentTime(java.time.LocalDateTime incidentTime) {
		this.incidentTime = incidentTime;
	}

	public dedupCases(java.lang.String policyNo,
			java.time.LocalDateTime incidentTime, java.lang.String location,
			java.lang.String vehicleRegNo, java.lang.String saId,
			java.lang.String customerInitials,
			java.lang.String customerSurname, java.lang.String dateOfBirth,
			java.lang.String vehicleIncidentType,
			java.lang.String vehicleIncidentSubtype,
			java.lang.String policyHolderId, java.lang.String caseStatus) {
		this.policyNo = policyNo;
		this.incidentTime = incidentTime;
		this.location = location;
		this.vehicleRegNo = vehicleRegNo;
		this.saId = saId;
		this.customerInitials = customerInitials;
		this.customerSurname = customerSurname;
		this.dateOfBirth = dateOfBirth;
		this.vehicleIncidentType = vehicleIncidentType;
		this.vehicleIncidentSubtype = vehicleIncidentSubtype;
		this.policyHolderId = policyHolderId;
		this.caseStatus = caseStatus;
	}

}